# 服务注册与发现
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true # 是否注册自己到Eureka服务中心
    fetchRegistry: true # 是否从Eureka服务中心获取注册信息
    serviceUrl: # 设置Eureka服务中心地址
      defaultZone: http://localhost:20002/eureka/

spring:
  boot:
    admin:
      url: http://localhost:20001
