# 服务注册与发现
eureka:
  client:
    registerWithEureka: true # 是否注册自己到Eureka服务中心
    fetchRegistry: true # 是否从Eureka服务中心获取注册信息
    serviceUrl: # 设置Eureka服务中心地址
      defaultZone: http://192.168.20.61:20000/eureka/,http://192.168.20.62:20000/eureka/