server:
  port: 20000
spring:
  application:
    name: ms-config-center
  boot:
    admin:
      url: http://localhost:20001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Paleozoic/spring_cloud_demo/
          default-label: config-repo
