# 服务的注册与发现eureka
server:
  port: 20002
spring:
  application:
    name: ms-registry-discovery
  boot:
    admin:
      url: http://localhost:20001
  cloud:
    config:
        uri: http://localhost:20000
management:
      security:
        enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 不注册自己到Eureka服务中心
    fetchRegistry: false # 从Eureka服务中心获取注册信息
    serviceUrl: # 设置Eureka服务中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
