spring:
  application:
    name: ms-config-center
  boot:
    admin:
      url: http://192.168.20.61:20005
  cloud:
    config:
      server:
        git:
          uri: http://wiki.xxx.cn/Paleo/config-repo-nodes.git #内网git
          default-label: config-repo-nodes

management:
  security:
    enabled: false

# 服务注册与发现
eureka:
  client:
    registerWithEureka: true # 是否注册自己到Eureka服务中心
    fetchRegistry: true # 是否从Eureka服务中心获取注册信息
    serviceUrl: # 设置Eureka服务中心地址
      defaultZone: http://192.168.20.61:20000/eureka/,http://192.168.20.62:20000/eureka/,http://192.168.20.63:20000/eureka/
